# Generated by Django 2.2.1 on 2020-08-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('counter', models.IntegerField()),
            ],
            options={
                'unique_together': {('user_id', 'counter')},
            },
        ),
        migrations.CreateModel(
            name='Member_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=100)),
                ('activity_periods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Date')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False)),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Member_Details')),
            ],
        ),
    ]
